### ISSUE TITLE
Genereate ef model

### ISSUE THREAD

**Issue by Diaskhan** [dr-noise/PolyGen#2]
Could ure solution generate a few models and refernces beteeen them ? 

For example have some student and his referenced to class or school ?

**Comment by dr-noise** [comment]
@Diaskhan that's exactly what it does. Check Readme for a sample.

**Comment by Diaskhan** [comment]
Maybe we shall build a gui configurator that ?

**Comment by dr-noise** [comment]
We surely can, I just don't have any time right now :)

**Comment by dr-noise** [comment]
@Diaskhan we surely can, I just don't have any time right now :)
