### ISSUE TITLE
Json format (ГУИ редактор)

### ISSUE THREAD

**Issue by Diaskhan** [dr-noise/PolyGen#3]
Maybe We could do Json format and generate from JSON
Object classes ??

**Comment by dr-noise** [comment]
@Diaskhan yes, this entire library should be exposed as an API and we should build a web client for it.

**Comment by Diaskhan** [comment]
**dr-noise** 
I have a few question about metadate repository 
![image](https://user-images.githubusercontent.com/15046677/36242403-11826182-1246-11e8-8b68-0e313438ca64.png)


1.There have a fields that have a referenced.
In gui must be drop-down list to a refrenced fields.
The medata of fields must stored in DB.
If I will develop js gui, and data of fields will stored in db could generate it from db ??

Db must have this fields.
![image](https://user-images.githubusercontent.com/15046677/36242647-49be8d4a-1247-11e8-9212-17a5e09f2d9a.png)

**Comment by Diaskhan** [comment]
Could regesign u're api to make it work with this DB stricture ???

**Comment by Diaskhan** [comment]
Или под веб ГУИ редактором ты имел виду следующее  ???
![image](https://user-images.githubusercontent.com/15046677/36247875-c22eb238-125f-11e8-8d24-cac48e20da39.png)

**Comment by Diaskhan** [comment]
Dr-noise What di U ????
